# Generated by Django 4.1.8 on 2023-04-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productos",
            name="foto",
        ),
        migrations.AddField(
            model_name="productos",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="item-images/"),
        ),
    ]
