# Generated by Django 4.1.8 on 2023-04-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_remove_productos_foto_productos_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="caracteristicas",
            options={
                "verbose_name": "Caracteristica",
                "verbose_name_plural": "Caracteristicas",
            },
        ),
        migrations.AlterModelOptions(
            name="categorias",
            options={"verbose_name": "Categoría", "verbose_name_plural": "Categorias"},
        ),
        migrations.AlterModelOptions(
            name="productos",
            options={"verbose_name": "Producto", "verbose_name_plural": "Productos"},
        ),
        migrations.AddField(
            model_name="productos",
            name="caracteristicas",
            field=models.ManyToManyField(to="product.caracteristicas"),
        ),
        migrations.DeleteModel(
            name="CaracteristicaPorProducto",
        ),
    ]
