# Generated by Django 4.1.8 on 2023-05-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_productos_cantidad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productos",
            name="nombre",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
