# Generated by Django 4.1.8 on 2023-04-27 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_caracteristicas_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorias",
            name="grupo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.categorias",
            ),
        ),
    ]
