# Generated by Django 4.1.8 on 2023-05-22 00:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_productos_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productos",
            name="precio",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
