# Generated by Django 4.1.8 on 2023-04-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_alter_caracteristicas_id_alter_categorias_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productos",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products"),
        ),
    ]
