# Generated by Django 4.1.8 on 2023-04-29 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_alter_productos_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="productos",
            name="creado",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
