# Generated by Django 4.1.8 on 2023-04-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_productos_creado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productos",
            name="caracteristicas",
        ),
        migrations.DeleteModel(
            name="Caracteristicas",
        ),
        migrations.AddField(
            model_name="productos",
            name="caracteristicas",
            field=models.CharField(default="a", max_length=600),
            preserve_default=False,
        ),
    ]
