# Generated by Django 4.1.8 on 2023-04-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_rename_caracteristicas_productos_descripcion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productos",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
    ]
