# Generated by Django 4.1.8 on 2023-05-07 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("buysSales", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="compras",
            options={"verbose_name": "Compra", "verbose_name_plural": "Compras"},
        ),
        migrations.AlterModelOptions(
            name="productosencarrito",
            options={
                "verbose_name": "Producto en carrito",
                "verbose_name_plural": "Productos en carrito",
            },
        ),
        migrations.AlterModelOptions(
            name="ventas",
            options={"verbose_name": "Venta", "verbose_name_plural": "Ventas"},
        ),
        migrations.AddField(
            model_name="ventas",
            name="creado",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
